### ISSUE TITLE
Crash with konkrete

### ISSUE THREAD

**Issue by SettingDust** [JumperOnJava/CustomCursor-comm#3]
Fabric 1.20.1
https://pastes.dev/uFGDOvojsg

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'customcursorcomm'!
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoClassDefFoundError: de/keksuccino/konkrete/events/client/GuiScreenEvent$DrawScreenEvent$Post
	at java.base@17.0.8/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base@17.0.8/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base@17.0.8/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at de.keksuccino.konkrete.events.EventHandler.registerEventsFrom(EventHandler.java:44)
	at io.github.jumperonjava.customcursorcomm.CustomCursorInit.entrypoint(CustomCursorInit.java:31)
	at io.github.jumperonjava.customcursorcomm.fabric.CustomcursorcommFabric.onInitializeClient(CustomcursorcommFabric.java:10)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 9 more
Caused by: java.lang.ClassNotFoundException: de.keksuccino.konkrete.events.client.GuiScreenEvent$DrawScreenEvent$Post
	at java.base@17.0.8/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base@17.0.8/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base@17.0.8/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 16 more
```

**Comment by inikishev** [comment]
same

**Comment by thrasos-dev** [comment]
I am also having this issue.

**Comment by PolyframeX** [comment]
Issue is present on latest version

**Comment by JumperOnJava** [comment]
Working on fix rn
Originally mod was made as commision for modpack, and i had to add compatibility with old fancy meny version which depends on old konkrete version 
I removed everything related to konkrete, and now it shouldn't crash, but i'm not sure about fancy menu compatibility

**Comment by JumperOnJava** [comment]
Mod is moving to different repository with some rewrites
Please download newer version of mod (2.0.0-beta2 as of now) and re-report your issue if it still occurs
https://github.com/JumperOnJava/CustomCursor
